version: "3.8"

networks:
  lablan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: payrwa1
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306" 
    networks:
      lablan:
        ipv4_address: 172.20.0.5

  web-01:
    build: ./backend
    container_name: web-01
    hostname: web-01
    depends_on:
      - mysql-db
    networks:
      lablan:
        ipv4_address: 172.20.0.11
    ports:
      - "2211:22"
      - "3000:8080"
    env_file:
      - ./backend/.env

  web-02:
    build: ./backend
    container_name: web-02
    hostname: web-02
    depends_on:
      - mysql-db
    networks:
      lablan:
        ipv4_address: 172.20.0.12
    ports:
      - "2212:22"
      - "3001:8080"
    env_file:
      - ./backend/.env

  lb-01:
    build: ./lb
    container_name: lb-01
    hostname: lb-01
    networks:
      lablan:
        ipv4_address: 172.20.0.10
    ports:
      - "2210:22"
      - "8080:80"