CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(10) NOT NULL,
  currency VARCHAR(10),
  phone VARCHAR(20)
);

CREATE TABLE transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  paid_to VARCHAR(255),
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20),
  description TEXT,
  currency VARCHAR(10),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
